// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "URL Shortener API": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/rymccue/goa-url-shortener-api/design
// --out=$(GOPATH)/src/github.com/rymccue/goa-url-shortener-api
// --version=v1.2.0-dirty

package client

import (
	"net/http"
)

// Url analytics (default view)
//
// Identifier: application/vnd.analytics+json; view=default
type Analytics struct {
	Hits *int `form:"hits,omitempty" json:"hits,omitempty" xml:"hits,omitempty"`
}

// DecodeAnalytics decodes the Analytics instance encoded in resp body.
func (c *Client) DecodeAnalytics(resp *http.Response) (*Analytics, error) {
	var decoded Analytics
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// A URL (default view)
//
// Identifier: application/vnd.url+json; view=default
type URL struct {
	// URL ID
	ID *int `form:"id,omitempty" json:"id,omitempty" xml:"id,omitempty"`
	// URL path key
	Path *string `form:"path,omitempty" json:"path,omitempty" xml:"path,omitempty"`
	// External url
	URL *string `form:"url,omitempty" json:"url,omitempty" xml:"url,omitempty"`
}

// DecodeURL decodes the URL instance encoded in resp body.
func (c *Client) DecodeURL(resp *http.Response) (*URL, error) {
	var decoded URL
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}
